[package]
name = "brewdb-jsonifier"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = { version = "1.13.1", features = ["attributes"] }
libsql = "0.9.19"
serde = "1.0.219"
serde_json = "1.0.141"


